#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80
# Querying Nginx at its root (/) with a GET request (requesting a page)
#    curl http://35.229.54.225/   --> returns string "Hello World!"
#   curl http://35.229.54.225/   --> returns header info

sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
sudo service nginx restart
