#!/usr/bin/env bash
# creating a scrhourpt that print hours
hour=0
while [ $hour -le 12 ]
do
	minutes=1
	echo "Hour: $hour"
	while [ $minutes -le 59 ]
	do
		echo $minutes
		minutes=$(( minutes + 1))
	done
	hour=$(( hour + 1))
done
